### ISSUE TITLE
Term count data

### ISSUE THREAD

**Issue by tsalo** [neuroquery/neuroquery_data#1]
Would it be possible for you to upload the count features in addition to the tf-idf features?

**Comment by jeromedockes** [comment]
> Would it be possible for you to upload the count data in addition to the tf-idf features?

I uploaded count data in `training_data/corpus_word_counts` (the
directory layout of the repo is still subject to change)

It contains separate counts for titles, keywords, abstracts and article
body for a vocabulary of around 7,000 terms.

I suggest we keep this issue open because I also plan to upload counts
for a much larger vocabulary, and maybe add keywords for some of the
articles that are missing them by combining multiple sources. I am not
sure that I will have time to do it this week, though.

**Comment by tsalo** [comment]
That's awesome! Thank you!

**Comment by jeromedockes** [comment]
> That's awesome! Thank you!

You're welcome!

**Comment by jeromedockes** [comment]
> I suggest we keep this issue open because I also plan to upload counts for a much larger vocabulary

added in `corpus_word_counts_with_large_vocabulary`
